before_install: gem install bundler --pre
language: ruby
rvm:
 - 2.1.1
before_install:
  - gem --version
env:
  - RAILS=3.2.17
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
  - COVERALLS=1 bundle exec rspec spec/

